

/**
 * A definitive, robust function to get a readable string message from any error.
 * This function is designed to be "bulletproof" by defensively checking for
 * various error formats and translating common technical errors into user-friendly messages.
 *
 * @param error The error to process.
 * @returns A string representation of the error message.
 */

/* SQL Script to fix infinite recursion in RLS policies, enrollment permissions, analytics, and admin functions */
export const FIX_RECURSION_SQL = `
-- MASTER SCHEMA SYNC SCRIPT (V30 - ANALYTICS FIX)
-- Run this in Supabase SQL Editor.

BEGIN;

-- 1. NOTIFICATIONS TABLE FIX (CRITICAL)
-- Handle transition from Enum to Text for 'type' column safely.
DO $$ 
BEGIN
    -- Check if notifications table exists
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'notifications') THEN
        
        -- Check if 'type' column exists
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'type') THEN
            -- Change to text if it exists (handles enum to text conversion)
            BEGIN
                ALTER TABLE public.notifications ALTER COLUMN type TYPE text USING type::text;
                ALTER TABLE public.notifications ALTER COLUMN type SET DEFAULT 'system_notification';
            EXCEPTION WHEN OTHERS THEN
                -- Fallback: If conversion fails (e.g. weird enum state), re-create column
                ALTER TABLE public.notifications DROP COLUMN type;
                ALTER TABLE public.notifications ADD COLUMN type text DEFAULT 'system_notification';
            END;
        ELSE
            -- Column missing (likely dropped by previous CASCADE), add it back
            ALTER TABLE public.notifications ADD COLUMN type text DEFAULT 'system_notification';
        END IF;

        -- Ensure metadata column exists for game invites
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'metadata') THEN
            ALTER TABLE public.notifications ADD COLUMN metadata jsonb DEFAULT '{}'::jsonb;
        END IF;

    END IF;
END $$;

-- Drop the legacy enum type if it exists. 
-- CASCADE will drop any functions/triggers explicitly depending on it.
DROP TYPE IF EXISTS public.notification_type CASCADE;

-- 2. Cleanup Legacy Triggers (CRITICAL for "Subject Creation" Error)
DROP TRIGGER IF EXISTS on_subject_created ON public.subjects;
DROP FUNCTION IF EXISTS notify_on_subject_creation; 
DROP TRIGGER IF EXISTS on_enrollment_request ON public.subject_enrollments;
DROP FUNCTION IF EXISTS notify_teacher_on_enrollment;

-- 3. Create Enums (Idempotent)
DO $$ BEGIN CREATE TYPE public.theme_preference AS ENUM ('light', 'dark', 'system'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.card_color AS ENUM ('pink', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'gray'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.game_mode AS ENUM ('CLASSIC', 'QUIZ'); EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 4. Ensure Tables Exist
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  full_name text,
  course text,
  role text DEFAULT 'Student'::text,
  preferred_theme public.theme_preference DEFAULT 'system'::public.theme_preference,
  avatar_url text,
  created_at timestamptz DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz DEFAULT timezone('utc'::text, now()),
  email text
);

CREATE TABLE IF NOT EXISTS public.subjects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  subject_code text UNIQUE DEFAULT SUBSTRING(md5((random())::text) FROM 1 FOR 6),
  teacher_id uuid REFERENCES auth.users(id),
  created_at timestamptz DEFAULT now(),
  description text,
  image_url text
);

-- Ensure subject_code column exists
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'subjects' AND column_name = 'subject_code') THEN
        ALTER TABLE public.subjects ADD COLUMN subject_code text DEFAULT SUBSTRING(md5((random())::text) FROM 1 FOR 6);
        ALTER TABLE public.subjects ADD CONSTRAINT subjects_subject_code_key UNIQUE (subject_code);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id uuid REFERENCES public.profiles(id),
  actor_id uuid REFERENCES public.profiles(id),
  type text DEFAULT 'system_notification'::text,
  related_entity_id bigint,
  related_subject_id bigint REFERENCES public.subjects(id),
  metadata jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- (Re)Create other tables if needed...
CREATE TABLE IF NOT EXISTS public.decks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id),
  title text,
  color public.card_color,
  mode public.game_mode,
  created_at timestamptz DEFAULT now(),
  is_assessment boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.study_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id),
  deck_id bigint REFERENCES public.decks(id),
  completed_at timestamptz DEFAULT now(),
  score_percentage smallint,
  correct_count integer,
  total_cards integer,
  subject_id bigint REFERENCES public.subjects(id)
);

CREATE TABLE IF NOT EXISTS public.subject_enrollments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id bigint REFERENCES public.subjects(id),
  student_id uuid REFERENCES public.profiles(id),
  teacher_id uuid, 
  enrolled_at timestamptz DEFAULT now(),
  status text DEFAULT 'pending'::text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.subject_decks (
  subject_id bigint REFERENCES public.subjects(id),
  deck_id bigint REFERENCES public.decks(id),
  added_at timestamptz DEFAULT now(),
  teacher_id uuid,
  PRIMARY KEY (subject_id, deck_id)
);

CREATE TABLE IF NOT EXISTS public.cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deck_id bigint REFERENCES public.decks(id),
  question text,
  answer text,
  options jsonb,
  correctanswer text
);

CREATE TABLE IF NOT EXISTS public.friendships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user1_id uuid REFERENCES public.profiles(id),
  user2_id uuid REFERENCES public.profiles(id),
  requester_id uuid REFERENCES public.profiles(id),
  status text DEFAULT 'pending'::text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.game_rooms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host_id uuid REFERENCES public.profiles(id),
  guest_id uuid REFERENCES public.profiles(id),
  config jsonb,
  cards jsonb,
  game_state jsonb,
  status text DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);

-- 5. RLS Policies (Reset to ensure consistency)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE decks ENABLE ROW LEVEL SECURITY;
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE subject_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE subject_decks ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE friendships ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_rooms ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to prevent conflicts/recursion
DROP POLICY IF EXISTS "Public Profiles" ON profiles;
DROP POLICY IF EXISTS "Self Update Profile" ON profiles;
DROP POLICY IF EXISTS "Self Insert Profile" ON profiles;
DROP POLICY IF EXISTS "Public Read Subjects" ON subjects;
DROP POLICY IF EXISTS "Teacher Manage Subjects" ON subjects;
DROP POLICY IF EXISTS "Owner Manage Decks" ON decks;
DROP POLICY IF EXISTS "Public Read Decks" ON decks;
DROP POLICY IF EXISTS "Public Read Cards" ON cards;
DROP POLICY IF EXISTS "Owner Manage Cards" ON cards;
DROP POLICY IF EXISTS "Student Enroll" ON subject_enrollments;
DROP POLICY IF EXISTS "View Enrollments" ON subject_enrollments;
DROP POLICY IF EXISTS "Teacher Manage Enrollments" ON subject_enrollments;
DROP POLICY IF EXISTS "Delete Enrollments" ON subject_enrollments;
DROP POLICY IF EXISTS "Read Subject Decks" ON subject_decks;
DROP POLICY IF EXISTS "Manage Subject Decks" ON subject_decks;
DROP POLICY IF EXISTS "Users Manage Sessions" ON study_sessions;
DROP POLICY IF EXISTS "Teachers View Subject Sessions" ON study_sessions;
DROP POLICY IF EXISTS "Users Manage Own Notifications" ON notifications;
DROP POLICY IF EXISTS "System Insert Notifications" ON notifications;
DROP POLICY IF EXISTS "Friendship Access" ON friendships;
DROP POLICY IF EXISTS "Game Participants" ON game_rooms;

-- Re-create Policies
CREATE POLICY "Public Profiles" ON profiles FOR SELECT USING (true);
CREATE POLICY "Self Update Profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Self Insert Profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Public Read Subjects" ON subjects FOR SELECT USING (true);
CREATE POLICY "Teacher Manage Subjects" ON subjects FOR ALL USING (teacher_id = auth.uid());

CREATE POLICY "Owner Manage Decks" ON decks FOR ALL USING (user_id = auth.uid());
CREATE POLICY "Public Read Decks" ON decks FOR SELECT USING (true);

CREATE POLICY "Public Read Cards" ON cards FOR SELECT USING (true);
CREATE POLICY "Owner Manage Cards" ON cards FOR ALL USING (
    EXISTS (SELECT 1 FROM decks WHERE id = cards.deck_id AND user_id = auth.uid())
);

CREATE POLICY "Student Enroll" ON subject_enrollments FOR INSERT WITH CHECK (student_id = auth.uid());
CREATE POLICY "View Enrollments" ON subject_enrollments FOR SELECT USING (
    student_id = auth.uid() OR 
    EXISTS (SELECT 1 FROM subjects WHERE id = subject_id AND teacher_id = auth.uid())
);
CREATE POLICY "Teacher Manage Enrollments" ON subject_enrollments FOR UPDATE USING (
    EXISTS (SELECT 1 FROM subjects WHERE id = subject_id AND teacher_id = auth.uid())
);
CREATE POLICY "Delete Enrollments" ON subject_enrollments FOR DELETE USING (
    student_id = auth.uid() OR 
    EXISTS (SELECT 1 FROM subjects WHERE id = subject_id AND teacher_id = auth.uid())
);

CREATE POLICY "Read Subject Decks" ON subject_decks FOR SELECT USING (true);
CREATE POLICY "Manage Subject Decks" ON subject_decks FOR ALL USING (
    EXISTS (SELECT 1 FROM subjects WHERE id = subject_id AND teacher_id = auth.uid())
);

CREATE POLICY "Users Manage Sessions" ON study_sessions FOR ALL USING (user_id = auth.uid());
CREATE POLICY "Teachers View Subject Sessions" ON study_sessions FOR SELECT USING (
    subject_id IS NOT NULL AND EXISTS (SELECT 1 FROM subjects WHERE id = subject_id AND teacher_id = auth.uid())
);

-- Updated: Allow both recipient and actor (sender) to manage the notification. 
-- This allows a sender to cancel (delete) an invite they sent.
CREATE POLICY "Users Manage Own Notifications" ON notifications FOR ALL USING (
    recipient_id = auth.uid() OR actor_id = auth.uid()
);
CREATE POLICY "System Insert Notifications" ON notifications FOR INSERT WITH CHECK (true);

CREATE POLICY "Friendship Access" ON friendships FOR ALL USING (auth.uid() = user1_id OR auth.uid() = user2_id OR auth.uid() = requester_id);

CREATE POLICY "Game Participants" ON game_rooms FOR ALL USING (auth.uid() = host_id OR auth.uid() = guest_id);

-- 6. Functions & Triggers
-- Re-define helper functions with text types
CREATE OR REPLACE FUNCTION enroll_in_subject(subject_code_to_enroll text) RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_subject_id bigint;
  v_teacher_id uuid;
BEGIN
  SELECT id, teacher_id INTO v_subject_id, v_teacher_id FROM subjects WHERE subject_code = subject_code_to_enroll;
  IF v_subject_id IS NULL THEN RETURN json_build_object('success', false, 'message', 'Invalid code.'); END IF;
  
  INSERT INTO subject_enrollments (subject_id, student_id, status, teacher_id) VALUES (v_subject_id, auth.uid(), 'pending', v_teacher_id) ON CONFLICT DO NOTHING;
  
  -- Insert notification safely
  BEGIN
    INSERT INTO notifications (recipient_id, actor_id, type, related_entity_id, related_subject_id)
    VALUES (v_teacher_id, auth.uid(), 'enrollment_request', (SELECT id FROM subject_enrollments WHERE subject_id = v_subject_id AND student_id = auth.uid()), v_subject_id);
  EXCEPTION WHEN OTHERS THEN NULL; END;
  
  RETURN json_build_object('success', true, 'message', 'Request sent.');
END;
$$;

CREATE OR REPLACE FUNCTION approve_enrollment_request(enrollment_id bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_student_id uuid;
  v_subject_id bigint;
BEGIN
  UPDATE subject_enrollments SET status = 'approved' WHERE id = enrollment_id RETURNING student_id, subject_id INTO v_student_id, v_subject_id;
  IF v_student_id IS NOT NULL THEN
    BEGIN
        INSERT INTO notifications (recipient_id, actor_id, type, related_entity_id, related_subject_id)
        VALUES (v_student_id, auth.uid(), 'enrollment_approved', enrollment_id, v_subject_id);
    EXCEPTION WHEN OTHERS THEN NULL; END;
  END IF;
END;
$$;

-- Utility functions
CREATE OR REPLACE FUNCTION delete_subject(subject_id_to_delete bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  DELETE FROM subjects WHERE id = subject_id_to_delete AND teacher_id = auth.uid();
END;
$$;

CREATE OR REPLACE FUNCTION delete_deck(deck_id_to_delete bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    DELETE FROM decks WHERE id = deck_id_to_delete AND user_id = auth.uid();
END;
$$;

CREATE OR REPLACE FUNCTION unenroll_from_subject(subject_id_to_unenroll bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  DELETE FROM subject_enrollments WHERE subject_id = subject_id_to_unenroll AND student_id = auth.uid();
END;
$$;

CREATE OR REPLACE FUNCTION get_subject_analytics(p_subject_id bigint) 
RETURNS TABLE (student_name text, deck_title text, score_percentage integer, completed_at timestamptz) 
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY 
    SELECT 
        p.full_name, 
        d.title, 
        ss.score_percentage::integer, -- Explicit cast to integer to match RETURNS TABLE
        ss.completed_at 
    FROM study_sessions ss 
    JOIN profiles p ON ss.user_id = p.id 
    JOIN decks d ON ss.deck_id = d.id 
    WHERE ss.subject_id = p_subject_id;
END;
$$;

-- Admin Functions
CREATE OR REPLACE FUNCTION admin_search_students(search_term text) RETURNS TABLE (id uuid, full_name text, email text, course text, avatar_url text, created_at timestamptz) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY SELECT p.id, p.full_name, p.email, p.course, p.avatar_url, p.created_at FROM profiles p WHERE p.role = 'Student' AND (search_term IS NULL OR p.full_name ILIKE '%'||search_term||'%' OR p.email ILIKE '%'||search_term||'%');
END;
$$;

CREATE OR REPLACE FUNCTION admin_search_teachers(search_term text) RETURNS TABLE (id uuid, full_name text, email text, course text, avatar_url text, created_at timestamptz, subject_count bigint) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY SELECT p.id, p.full_name, p.email, p.course, p.avatar_url, p.created_at, (SELECT COUNT(*) FROM subjects s WHERE s.teacher_id = p.id) FROM profiles p WHERE p.role = 'Teacher' AND (search_term IS NULL OR p.full_name ILIKE '%'||search_term||'%' OR p.email ILIKE '%'||search_term||'%');
END;
$$;

CREATE OR REPLACE FUNCTION admin_search_subjects(search_term text) RETURNS TABLE (id bigint, title text, subject_code text, teacher_name text, student_count bigint, created_at timestamptz) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY SELECT s.id, s.title, s.subject_code, p.full_name, (SELECT COUNT(*) FROM subject_enrollments se WHERE se.subject_id = s.id AND se.status = 'approved'), s.created_at FROM subjects s JOIN profiles p ON s.teacher_id = p.id WHERE (search_term IS NULL OR s.title ILIKE '%'||search_term||'%' OR s.subject_code ILIKE '%'||search_term||'%' OR p.full_name ILIKE '%'||search_term||'%');
END;
$$;

CREATE OR REPLACE FUNCTION admin_delete_user(user_id_to_delete uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    DELETE FROM auth.users WHERE id = user_id_to_delete;
END;
$$;

CREATE OR REPLACE FUNCTION admin_delete_subject(subject_id_to_delete bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    DELETE FROM subjects WHERE id = subject_id_to_delete;
END;
$$;

CREATE OR REPLACE FUNCTION get_admin_stats() RETURNS TABLE (total_users bigint, student_users bigint, teacher_users bigint, total_subjects bigint) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN QUERY SELECT (SELECT COUNT(*) FROM profiles), (SELECT COUNT(*) FROM profiles WHERE role = 'Student'), (SELECT COUNT(*) FROM profiles WHERE role = 'Teacher'), (SELECT COUNT(*) FROM subjects);
END;
$$;

CREATE OR REPLACE FUNCTION get_admin_activity_trends() RETURNS TABLE (activity_date text, new_users bigint, study_sessions bigint) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN QUERY WITH dates AS (SELECT generate_series(CURRENT_DATE - INTERVAL '6 days', CURRENT_DATE, '1 day'::interval)::date AS day)
  SELECT to_char(d.day, 'Mon DD'), (SELECT COUNT(*) FROM profiles p WHERE p.created_at::date = d.day), (SELECT COUNT(*) FROM study_sessions s WHERE s.completed_at::date = d.day) FROM dates d ORDER BY d.day ASC;
END;
$$;

CREATE OR REPLACE FUNCTION get_friends_and_requests() RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_friends json;
  v_requests json;
BEGIN
  SELECT json_agg(json_build_object('friendship_id', f.id, 'id', p.id, 'full_name', p.full_name, 'avatar_url', p.avatar_url, 'course', p.course)) INTO v_friends
  FROM friendships f JOIN profiles p ON (CASE WHEN f.user1_id = v_user_id THEN f.user2_id ELSE f.user1_id END) = p.id
  WHERE (f.user1_id = v_user_id OR f.user2_id = v_user_id) AND f.status = 'accepted';

  SELECT json_agg(json_build_object('friendship_id', f.id, 'id', p.id, 'full_name', p.full_name, 'avatar_url', p.avatar_url, 'course', p.course)) INTO v_requests
  FROM friendships f JOIN profiles p ON f.requester_id = p.id
  WHERE (f.user1_id = v_user_id OR f.user2_id = v_user_id) AND f.requester_id != v_user_id AND f.status = 'pending';

  RETURN json_build_object('friends', COALESCE(v_friends, '[]'::json), 'requests', COALESCE(v_requests, '[]'::json));
END;
$$;

CREATE OR REPLACE FUNCTION search_students(search_term text) RETURNS TABLE (id uuid, full_name text, avatar_url text, course text) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY SELECT p.id, p.full_name, p.avatar_url, p.course FROM profiles p WHERE p.role = 'Student' AND p.id != auth.uid() AND p.full_name ILIKE '%'||search_term||'%' LIMIT 20;
END;
$$;

CREATE OR REPLACE FUNCTION update_deck_with_cards(p_deck_id bigint, p_title text, p_is_assessment boolean, p_cards jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    card_item jsonb;
BEGIN
    -- Update deck title and assessment status
    UPDATE decks SET title = p_title, is_assessment = p_is_assessment WHERE id = p_deck_id AND user_id = auth.uid();
    
    -- Delete existing cards
    DELETE FROM cards WHERE deck_id = p_deck_id;
    
    -- Insert new cards
    FOR card_item IN SELECT * FROM jsonb_array_elements(p_cards)
    LOOP
        INSERT INTO cards (deck_id, question, answer, options, correctanswer)
        VALUES (
            p_deck_id,
            card_item->>'question',
            card_item->>'answer',
            card_item->'options',
            card_item->>'correctanswer'
        );
    END LOOP;
END;
$$;

-- GAME RPCs
CREATE OR REPLACE FUNCTION start_game(p_room_id bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_initial_state jsonb;
BEGIN
    -- Initial state: both scores 0, index 0, phase countdown (triggers frontend overlay)
    v_initial_state := jsonb_build_object(
        'phase', 'countdown',
        'current_card_index', 0,
        'host_score', 0,
        'guest_score', 0,
        'round_answers', '{}'::jsonb
    );

    UPDATE game_rooms 
    SET status = 'active', game_state = v_initial_state
    WHERE id = p_room_id AND (guest_id = auth.uid() OR host_id = auth.uid());

    -- Cleanup Invite
    DELETE FROM notifications WHERE related_entity_id = p_room_id AND type = 'game_invite';
END;
$$;

CREATE OR REPLACE FUNCTION submit_game_answer(p_room_id bigint, p_player_role text, p_score_add integer, p_answer text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_game_state jsonb;
    v_round_answers jsonb;
    v_current_index int;
    v_cards jsonb;
    v_card_count int;
BEGIN
    -- Lock row
    SELECT game_state, cards INTO v_game_state, v_cards FROM game_rooms WHERE id = p_room_id FOR UPDATE;
    
    v_round_answers := v_game_state->'round_answers';
    v_current_index := (v_game_state->>'current_card_index')::int;
    v_card_count := jsonb_array_length(v_cards);

    -- Update Score
    IF p_player_role = 'host' THEN
        v_game_state := jsonb_set(v_game_state, '{host_score}', ((v_game_state->>'host_score')::int + p_score_add)::text::jsonb);
    ELSE
        v_game_state := jsonb_set(v_game_state, '{guest_score}', ((v_game_state->>'guest_score')::int + p_score_add)::text::jsonb);
    END IF;

    -- Record Answer
    v_round_answers := jsonb_set(v_round_answers, ('{'||p_player_role||'}')::text[], ('"'||p_answer||'"')::jsonb);
    v_game_state := jsonb_set(v_game_state, '{round_answers}', v_round_answers);

    -- Check if round complete (both answered)
    IF (v_round_answers ? 'host') AND (v_round_answers ? 'guest') THEN
        -- Move to next round
        v_current_index := v_current_index + 1;
        v_game_state := jsonb_set(v_game_state, '{current_card_index}', to_jsonb(v_current_index));
        v_game_state := jsonb_set(v_game_state, '{round_answers}', '{}'::jsonb);
        
        -- Check Game Over
        IF v_current_index >= v_card_count THEN
            v_game_state := jsonb_set(v_game_state, '{phase}', '"finished"');
        END IF;
    END IF;

    UPDATE game_rooms SET game_state = v_game_state WHERE id = p_room_id;
END;
$$;

-- Enable Realtime
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR TABLE notifications, game_rooms;

COMMIT;
`;

export const getErrorMessage = (error: unknown): string => {
    // 1. Handle explicit strings first.
    if (typeof error === 'string') {
        // Fallback catch for the specific message reported by the user, forcing the fix UI.
        if (error.includes("Unable to save: A related record") || error.includes("User Profile) is missing")) {
             return 'DATABASE_RECURSION_ERROR:Profile Missing. Your account is missing a required profile record. Run the SQL fix below.';
        }
        return error;
    }

    let message = '';

    // 2. Handle objects with a string 'message' property (most common for Supabase/API errors).
    if (error && typeof error === 'object') {
        const errObj = error as Record<string, unknown>;
        if (typeof errObj.message === 'string') {
            message = errObj.message;
        } else if (typeof errObj.error_description === 'string') {
            message = errObj.error_description;
        }
    } else if (error instanceof Error) {
        message = error.message;
    }

    // Specific catch for the persisting foreign key error
    if (message.includes('fk_subject_code_exists') || message.includes('subject_codes') || message.includes('relation "public.subject_codes" does not exist')) {
        return 'DATABASE_ERROR: Obsolete database constraint "fk_subject_code_exists" detected. The system is trying to check a table that should not exist. Please run the SQL fix script in Settings.';
    }
    
    // Fix for: operator does not exist: text = notification_type
    if (message.includes('operator does not exist') && (message.includes('notification_type') || message.includes('text ='))) {
        return 'DATABASE_ERROR: Type Mismatch (Notification Enum). The database is using an old enum type. Run the SQL fix script in Settings.';
    }
    
    // Fix for: type "notification_type" does not exist
    if (message.includes('type "notification_type" does not exist')) {
        return 'DATABASE_ERROR: Type Mismatch (Notification Enum Missing). The database is trying to use a missing enum type. Run the SQL fix script in Settings.';
    }

    // Translate common technical errors
    if (message.includes('duplicate key value violates unique constraint')) {
        return 'An item with this name or code already exists. Please choose a different one.';
    }
    
    // Improve Foreign Key Violation and RLS Error Messaging to trigger SQL Fix
    if (message.includes('violates foreign key constraint') || message.includes('violates row-level security policy') || message.includes('violates check constraint')) {
        // "update or delete on table" specifically implies that the current item cannot be removed because other tables reference it.
        if (message.includes('update or delete on table') && !message.includes('profiles')) {
             // This logic is now likely handled by CASCADE, but kept for other edge cases
             return 'This item cannot be deleted because it is being used by other records (e.g., enrolled students or linked decks).';
        }
        // "insert or update on table" implies the item we are trying to save references a parent that doesn't exist or permissions are wrong.
        return 'DATABASE_ERROR: Database Permission/Sync Issue. Your account is missing a required profile record or a database policy is blocking the action. Run the SQL fix script in Settings.';
    }

    if (message.includes('User not found')) {
        return 'No user was found with the provided credentials.';
    }
     if (message.includes('Invalid login credentials')) {
        return 'Invalid email or password. Please try again.';
    }
    if (message.includes('structure of query does not match function result type')) {
        return 'DATABASE_ERROR: Data Type Mismatch. The "get_subject_analytics" function definition is outdated. Please run the SQL fix script in Settings.';
    }
    if (message.includes('Could not choose the best candidate function')) {
        return 'SCHEMA_CACHE_ERROR:The database has conflicting function versions. Please run the updated SQL script in the Supabase editor to resolve this.';
    }
    if (message.includes('relation') && message.includes('does not exist')) {
         console.error("CRITICAL DATABASE ERROR: Missing Database Relation.");
         console.log("SQL FIX:\n", FIX_RECURSION_SQL);
         return 'DATABASE_ERROR: Missing database relations (tables/views). Please run the fixed SQL script in Settings.';
    }
    if (message.includes('function') && message.includes('does not exist')) {
         console.error("CRITICAL DATABASE ERROR: Missing Database Function.");
         console.log("SQL FIX:\n", FIX_RECURSION_SQL);
         return 'DATABASE_ERROR: Missing database functions. Please run the fixed SQL script in Settings.';
    }
    if (message.includes('column') && message.includes('does not exist')) {
         console.error("CRITICAL DATABASE ERROR: Schema mismatch (missing column).");
         console.log("SQL FIX:\n", FIX_RECURSION_SQL);
         return 'DATABASE_ERROR: Database schema mismatch (missing column). Please run the fixed SQL script in Settings.';
    }
    if (message.includes('stack depth limit exceeded') || message.includes('infinite recursion')) {
        console.error("CRITICAL DATABASE ERROR: Infinite recursion in RLS policies detected.");
        console.log("SQL FIX:\n", FIX_RECURSION_SQL); // Log to console for easy access
        return 'DATABASE_ERROR: Infinite recursion detected in database policies. Please run the fixed SQL script in Settings.';
    }
    if (message.includes('cannot alter type of a column used by a view or rule')) {
        console.error("CRITICAL DATABASE ERROR: Dependent views blocking schema update.");
        console.log("SQL FIX:\n", FIX_RECURSION_SQL);
        return 'DATABASE_ERROR: Dependent views blocking update. Run the fixed SQL script to drop views and update schema.';
    }
    
    // Supabase paused / Network issues
    if (message.includes('Failed to fetch') || message.includes('NetworkError') || message.includes('503')) {
        return 'Unable to connect to the server. The database might be paused due to inactivity. Please check the Supabase dashboard to restore the project.';
    }

    if (message) {
        return message;
    }

    // 4. As a fallback, try to stringify the entire error object.
    try {
        const str = JSON.stringify(error, null, 2); // Pretty-print for better debugging
        if (str !== '{}') {
            return str;
        }
    } catch {
        // Fall through to the final, safest fallback.
    }

    // 5. The ultimate fallback.
    try {
        return `[Unstructured Error]: ${String(error)}`;
    } catch {
        return 'An unknown and un-stringifiable error occurred.';
    }
};